#!/bin/bash
# Attention 47 symbols!
./analyse.sh 'ADS.XETRA 1N8.XETRA AIL.XETRA AIR.XETRA ALV.XETRA 1NBA.XETRA ASME.XETRA AXA.XETRA BSD2.XETRA BAS.XETRA BAYN.XETRA BMW.XETRA BNP.XETRA DAI.XETRA BSN.XETRA DB1.XETRA DPW.XETRA DTE.XETRA ENL.XETRA GZF.XETRA ENI.XETRA IBE1.XETRA IXD1.XETRA INN1.XETRA IES.XETRA PPX.XETRA KC4.XETRA AHOG.XETRA PHI1.XETRA LOR.XETRA LIN.XETRA MOH.XETRA MUV2.XETRA NOA3.XETRA PER.XETRA 1TY.XETRA SNW.XETRA SAP.XETRA SND.XETRA SIE.XETRA TOTB.XETRA UNI2.XETRA SQU.XETRA VVU.XETRA VOW3.XETRA VNA.XETRA' $1 $2
