#!/bin/bash
# ./analyse-xetra100.sh 1 offline underrated 9
# Attention 100 symbols!
./analyse.sh 'MSF AMZ ABEC ABEA AHLA FB2A BRYN BRH VODJ 3V64 CMC JNJ WMT M4I NESM PRG SOBA UNH NCB HDI INL CCC3 BAC XONA WDP MOH 6MK CTP2 PFE PEP CHV ADB CIS NWT R6C R6C3 NVD NFC ORC BCO FOO LOR MDO SAP NOVC NKE ABL TRVC CTO 2M6 BRM TL0 4I1 4AB 2PP LLY HBC1 AMG ASMF ZEG SNW ASME ALD 1TY IBM NOVA TOTB 1YD LOM UNP 1NBA TII BPE CQD LIN BPE5 DAP GS7 IXD1 BIL AIR GIS GEC BMT SRB QCI AEC1 ENL ALV MMM VOW CVS GUI SIE KTF UPAB' $1 $2 $3 $4
