#!/bin/bash
#./analyse.sh 'BMW.XETRA EOAN.XETRA' 1 offline underrated 20
./analyse.sh 'ADS.XETRA ALV.XETRA BAS.XETRA BAYN.XETRA BMW.XETRA BEI.XETRA CBK.XETRA CON.XETRA 1COV.XETRA DAI.XETRA DBK.XETRA DB1.XETRA LHA.XETRA DPW.XETRA DTE.XETRA EOAN.XETRA FME.XETRA FRE.XETRA HEI.XETRA HEN.XETRA IFX.XETRA SDF.XETRA LIN.XETRA MRK.XETRA MUV2.XETRA RWE.XETRA SAP.XETRA SIE.XETRA TKA.XETRA VOW.XETRA VNA.XETRA MTX.XETRA DWNI.XETRA DHER.XETRA' $1 $2 $3 $4
