#!/bin/bash

# ./analyse-eurostoxx50.sh 1 offline 9 30
# Attention 43 symbols!
./analyse.sh 'ADS 1N8 AIL AIR ALV 1NBA ASME AXA BSD2 BAS BAYN BMW BNP DAI BSN DB1 DPW DTE ENL GZF ENI IBE1 IXD1 INN1 IES PPX AHOG PHI1 LOR LIN MOH MUV2 NOA3 1TY SNW SAP SND SIE TOTB SQU VVU VOW3 VNA' $1 $2 $3 $4
