# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Start analyse...
          export MARKET_STACK_ACCESS_KEY="a310b2410e8ca3c818a281b4eca0b86f"
          chmod +x ./analyse.sh
          chmod +x ./analyse-dax.sh
          chmod +x ./analyse-world.sh
          sh ./analyse-dax.sh offline
          #mail -s "Hello world" info@hopf-it.de
      - name: Send mail
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.ionos.de
          server_port: 465
          username: github@hopf-it.de
          password: gMarkus1!
          subject: Github Actions job result
          # Literal body:
          body: Build job of ${{github.repository}} completed successfully!
          # Read file contents as body:
          #body: file://./data/result.txt 
          to: info@hopf-it.de
          from: Github Stock Analyse # <github@hopf-it.de>
          # Optional content type (defaults to text/plain):
          content_type: text/html
          # Optional attachments:
          attachments: ./data/result.txt          
