name: CI StockAnalyse

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      symbolsParam:
        description: 'SYMBOLS - List of stock symbols like: "ADS.XETRA ALV.XETRA"'     
        required: true
        default: 'MSF.XETRA APC.XETRA AMZ.XETRA ABEC.XETRA ABEA.XETRA AHLA.XETRA FB2A.XETRA BRYN.XETRA BRH.XETRA VODJ.XETRA 3V64.XETRA CMC.XETRA JNJ.XETRA WMT.XETRA M4I.XETRA NESM.XETRA PRG.XETRA SOBA.XETRA UNH.XETRA NCB.XETRA HDI.XETRA INL.XETRA CCC3.XETRA BAC.XETRA XONA.XETRA WDP.XETRA MOH.XETRA 6MK.XETRA CTP2.XETRA PFE.XETRA PEP.XETRA CHV.XETRA ADB.XETRA CIS.XETRA NWT.XETRA R6C.XETRA R6C3.XETRA NVD.XETRA NFC.XETRA ORC.XETRA BCO.XETRA FOO.XETRA LOR.XETRA MDO.XETRA SAP.XETRA NOVC.XETRA NKE.XETRA ABL.XETRA UNI2.XETRA TRVC.XETRA CTO.XETRA 2M6.XETRA BRM.XETRA TL0.XETRA 4I1.XETRA 4AB.XETRA 2PP.XETRA LLY.XETRA HBC1.XETRA AMG.XETRA ASMF.XETRA ZEG.XETRA SNW.XETRA ASME.XETRA ALD.XETRA 1TY.XETRA IBM.XETRA NOVA.XETRA TOTB.XETRA 1YD.XETRA LOM.XETRA UNP.XETRA 1NBA.XETRA TII.XETRA BPE.XETRA CQD.XETRA LIN.XETRA BPE5.XETRA DAP.XETRA GS7.XETRA IXD1.XETRA BIL.XETRA AIR.XETRA GIS.XETRA GEC.XETRA BMT.XETRA SRB.XETRA QCI.XETRA AEC1.XETRA ENL.XETRA ALV.XETRA MMM.XETRA VOW.XETRA CVS.XETRA GUI.XETRA SIE.XETRA KTF.XETRA UPAB.XETRA'
      percentageParam:
        description: 'PERCENTAGE - "1" means 1 percent'     
        required: true
        default: '1'
      queryParam:
        description: 'QUERY - [online|offline]'     
        required: true
        default: 'online'
      ratedParam:
        description: 'RATED - [overrated|underrated]. List low/underrated stocks'     
        required: true
        default: 'underrated'
      stochasticParam:
        description: 'STOCHASTIC14 - "30" means 30/70 percent'     
        required: true
        default: '30'

  schedule:
  # Every 10 minutes
  # */10 * * * *  
  # Every Monday at 13:00
  # 0 13 * * 1
  # At 00:00 on Saturday
  # 0 0 * * 6 
  # Every 2nd day
  # 0 0 */2 * *
  - cron: "0 0 * * 6"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Run stock analyse
        run: |
          echo Start analyse...
          export MARKET_STACK_ACCESS_KEY=${{secrets.MARKET_STACK_ACCESS_KEY}}

          symbolsDefault='MSF.XETRA'
          percentageDefault=1
          queryDefault=offline
          ratedDefault=underrated
          stochasticDefault=30

          symbolsInput="${{github.event.inputs.symbolsParam}}"
          percentageInput=${{github.event.inputs.percentageParam}}
          queryInput=${{github.event.inputs.queryParam}}
          ratedInput=${{github.event.inputs.ratedParam}}
          stochasticInput=${{github.event.inputs.stochasticParam}}
          
          symbolsVar=${symbolsInput:-$symbolsDefault}
          percentageVar=${percentageInput:-$percentageDefault}
          queryVar=${queryInput:-$queryDefault}
          ratedVar=${ratedInput:-$ratedDefault}          
          stochasticVar=${stochasticInput:-$stochasticDefault}          
          
          chmod +x ./analyse.sh
          chmod +x ./analyse-dax2.sh
          chmod +x ./analyse-dax30.sh
          chmod +x ./analyse-eurostoxx50.sh
          chmod +x ./analyse-xetra100.sh
          chmod +x ./analyse-xetra1000.sh

          sh ./analyse.sh "$symbolsVar" $percentageVar $queryVar $ratedVar $stochasticVar

          git config user.email "markus@hopf-it.de"
          git config user.name "Markus Hopf"
          git add *
          git commit -am "save data"
          git push 

      - name: Send result.txt via email
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.ionos.de
          server_port: 465
          #username: github(ä)h...-it.de
          #password: g*1!
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}          
          subject: Github stock-analyse actions result
          # Literal body:
          #body: Build job of ${{github.repository}} completed successfully!
          # Read file contents as body:
          body: file://./out/result.txt
          to: info@hopf-it.de
          from: Github stock-analyse # <github@hopf-it.de>
          # Optional content type (defaults to text/plain):
          content_type: text/html
          # Optional attachments:
          attachments: ./out/result.txt, ./out/out.tar.gz       
