name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  schedule:
  # Every 10 minutes
  # */10 * * * *  
  # Every Monday at 1PM UTC (9AM EST)
  # 0 13 * * 1
  # At 00:00 on Saturday
  # 0 0 * * 6
  - cron: "0 0 * * 6"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Run analyse-dax30.sh 0.01 offline
        run: |
          echo Start analyse...
          export MARKET_STACK_ACCESS_KEY=${{secrets.MARKET_STACK_ACCESS_KEY}}
          chmod +x ./analyse.sh
          chmod +x ./analyse-dax30.sh
          chmod +x ./analyse-eurostoxx50.sh
          chmod +x ./analyse-xetra100.sh
          chmod +x ./analyse-xetra1000.sh
          sh ./analyse-dax30.sh 0.01 offline
      - name: Send result.txt as email
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.ionos.de
          server_port: 465
          #username: github(ä)h...-it.de
          #password: g*1!
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}          
          subject: Github Actions job result for stock-analyse analyse-dax30.sh 0.01
          # Literal body:
          #body: Build job of ${{github.repository}} completed successfully!
          # Read file contents as body:
          body: file://./data/result.txt 
          to: info@hopf-it.de
          from: Github stock-analyse # <github@hopf-it.de>
          # Optional content type (defaults to text/plain):
          content_type: text/html
          # Optional attachments:
          attachments: ./data/result.txt          
