# Is triggered:
#   1. on each push
#   2. curl 
#   3. manuell 
name: Dev

env:
  symbolsEnv: '*DBK' # If more then 1 symbol -> Error!
  percentageEnv: '1'
  queryEnv: 'offline'
  stochasticEnv: '9'
  RSIEnv: '25'

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  #pull_request:
    #branches: [ main ]
       
  # Can be triggered manually
  workflow_dispatch:
    inputs:
      symbolsParam:
        description: 'SYMBOLS - List of stock symbols like: "*DBK BEI". Own stocks marked *'
        required: true
        default: '*DBK *CRIN MOR FPE3 BC8 BEI'
      percentageParam:
        description: 'PERCENTAGE - "1" means 1 percent'     
        required: true
        default: '1'
      queryParam:
        description: 'QUERY - [online|offline]'     
        required: true
        default: 'offline'
      stochasticParam:
        description: 'STOCHASTIC14 - "9" means 9/91 percent (only single digit allowed!)'     
        required: true
        default: '9'
      RSIParam:
        description: 'RSI14 - "25" means 25/75 quote. (only 30 and less allowed!)'
        required: true
        default: '25'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - shell: bash
        run: |    
          echo "Bats Test"
          sh ./script/install-bats.sh
          /home/runner/.local/bin/bats -version
          mkdir temp
          rm -rf test/_result.html
          /home/runner/.local/bin/bats --tap script/*.bats

      # Runs a set of commands using the runners shell
      - name: Run Stock Analyse
        run: |
          echo "Start Stock Analyse ..."
          export MARKET_STACK_ACCESS_KEY1=${{secrets.MARKET_STACK_ACCESS_KEY1}}
          export MARKET_STACK_ACCESS_KEY2=${{secrets.MARKET_STACK_ACCESS_KEY2}}
          export MARKET_STACK_ACCESS_KEY3=${{secrets.MARKET_STACK_ACCESS_KEY3}}
          export MARKET_STACK_ACCESS_KEY4=${{secrets.MARKET_STACK_ACCESS_KEY4}}
          export MARKET_STACK_ACCESS_KEY5=${{secrets.MARKET_STACK_ACCESS_KEY5}}

          export GPG_PASSPHRASE=${{secrets.GPG_PASSPHRASE}}

          symbolsEnv=${{env.symbolsEnv}}
          percentageEnv=${{env.percentageEnv}}
          queryEnv=${{env.queryEnv}}
          stochasticEnv=${{env.stochasticEnv}}
          RSIEnv=${{env.RSIEnv}}

          symbolsInput="${{github.event.inputs.symbolsParam}}"
          percentageInput=${{github.event.inputs.percentageParam}}
          queryInput=${{github.event.inputs.queryParam}}
          stochasticInput=${{github.event.inputs.stochasticParam}}
          RSIInput=${{github.event.inputs.RSIParam}}
          
          symbolsVar=${symbolsInput:-$symbolsDefault}
          percentageVar=${percentageInput:-$percentageDefault}
          queryVar=${queryInput:-$queryDefault}         
          stochasticVar=${stochasticInput:-$stochasticDefault}          
          RSIVar=${RSIInput:-$RSIDefault}   

          symbolsVar=${symbolsVar:-$symbolsEnv}
          percentageVar=${percentageVar:-$percentageEnv}
          queryVar=${queryVar:-$queryEnv}         
          stochasticVar=${stochasticVar:-$stochasticEnv}          
          RSIVar=${RSIVar:-$RSIEnv}

          chmod +x ./analyse.sh

          sh ./analyse.sh "$symbolsVar" $percentageVar $queryVar $stochasticVar $RSIVar

          git config user.email ${{secrets.MAIL_ADRESS}}
          git config user.name "Markus Hopf"
          git add data/*.txt
          git add history/*.txt
          git add alarm/*.txt
          git add out/*.html
          git commit -am "Github Result ${{github.event_name}} ${{github.event.action}}" --allow-empty 
          git push
    
      - name: Send result via email
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.ionos.de
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Dev Result ${{github.event_name}} ${{github.event.action}}
          # Read file contents as body:
          body: file://out/_result.html
          to: ${{secrets.MAIL_ADRESS}}
          from: Github stock-analyse # <githubÄhopf-...de>
          # Optional content type (defaults to text/plain):
          content_type: text/html
          # Optional attachments:
          #attachments: out/_out.tar.gz
