# Is triggered:
#   1. curl 
#   2. manuell 
name: getInformerData

# Controls when the action will run. 
on:
  # Can be triggered with cURL
  repository_dispatch:
    types: [data] 
       
  # Can be triggered manually
  workflow_dispatch:
    inputs:
      symbolsParam:
        description: 'SYMBOLS - List of stock symbols like: "DBK BEI".'
        required: false
        default: ''

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Run curl (re)getInformerData
        run: |
          echo "Start (re)getInformerData ..."

          export GPG_PASSPHRASE=${{secrets.GPG_PASSPHRASE}}

          symbolDefault='${{github.event.client_payload.symbol}}'

          symbolInput="${{github.event.inputs.symbolParam}}"

          symbolVar=${symbolInput:-$symbolDefault}

          chmod +x ./script/curl/curl_getInformerData.sh

          gpg --batch --yes --passphrase "$GPG_PASSPHRASE" config/own_symbols.txt.gpg
          symbolsVar=$(sed 's/^/*/' config/own_symbols.txt | cut -f1 -d ' ' | tr '\n' ' ')
          rm -rf config/own_symbols.txt

          chmod +x ./curl_getInformerData.sh

          ./script/curl/curl_getInformerData.sh "$symbolVar"

          #low origin
          git config user.email ${{secrets.MAIL_ADRESS}}
          git config user.name "Markus Hopf"
          git add config/own_symbols.txt.gpg config/stock_symbols.txt
          git add data/*.txt
          git add history/*.txt
          git add alarm/*.txt
          git add buy/*.txt
          git add out/*.html
          git commit -am "Github ${{github.event_name}} ${{github.event.action}}" --allow-empty
          git push
          
      - name: Send result via email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.ionos.de
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Buy ${{github.event.client_payload.symbol}} Result ${{github.event_name}} ${{github.event.action}}
          # Read file contents as body:
          html_body: file://template/email.html
          #body: file://out/_result.html
          to: ${{secrets.MAIL_ADRESS}}
          from: Github stock-analyse # <githubÄhopf-...de>
          # Optional content type (defaults to text/plain):
          #content_type: text/html
          # Optional attachments:
          #attachments: out/_out.tar.gz
